### ISSUE TITLE
Superfish

### ISSUE THREAD

**Issue by ParimalSS** [openrestaurant/restaurant#1]
How to add superfish module in that theme?

**Comment by arshad** [comment]
1. Install the superfish module and configure.
2. Go to Structure --> Pages.
3. Find the Site Template and click edit
4. Click on Content in the Sidebar.
5. Click on the gear in the *Navigation* region and click *Add content*.
6. Find your superfish block and add it.
7. Click on Update and Save button (scroll to the bottom).

![screen_shot_restaurant_pages](https://cloud.githubusercontent.com/assets/124599/6167461/0a9cae28-b2d5-11e4-9ff8-ce227fb9a546.png)

**Comment by ParimalSS** [comment]
done....but after that it wont allow me for "customize button".

**Comment by arshad** [comment]
What do you mean by "customize button"? Can you send a screenshot? Thanks

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
