### ISSUE TITLE
Which modules patched

### ISSUE THREAD

**Issue by malasaad82** [openrestaurant/restaurant#10]
Hi,
Could you please list for us the modules you have been patched ... so we can update the rest of modules..  coz its very old now and all need udpate...

Thanks..

**Comment by arshad** [comment]
We don't keep a list of patches for now. To see a list of patches you will need to look at the make file under each restaurant modules.

But I just tagged release 7.x-1.0-beta11. This should have the latest updated modules and core.

**Comment by malasaad82** [comment]
I updated to beta10 and I saw there are a lot of modules need to update
like views..ctools etc..

**Comment by arshad** [comment]
You need beta11. Lots of new updates are in. See https://www.drupal.org/node/2469953

**Comment by arshad** [comment]
This issue was moved to openrestaurant/support#7
