### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by etron770** [openrestaurant/restaurant#13]
How can i translate f.e  Featured Menus   - Take a look at our most popular menus.
<div class="clearfix"> <div class="pull-left"> <h3>Featured Menus</h3> <p class="lead">Take a look at our most popular menus.</p> </div> <a href="/menus" class="btn btn-lg btn-success pull-right">All Menus</a> </div> 

HTML code is not allowed with the i18 module

**Comment by arshad** [comment]
This issue was moved to openrestaurant/support#6
