### ISSUE TITLE
Pantheon Installations don´t work

### ISSUE THREAD

**Issue by mori2k12bln** [openrestaurant/restaurant#14]
I tried to install it on Pantheon, but the "quick install" has a lot troubles - theme bugs, config bugs and is hardly showable to any interested client.

Did I do maybe something wrong?
It totally divers from that what´s visible on the demo page: http://dev-restaurant.gotpantheon.com/

I am now trying a local installation with "restaurant-7.x-1.0-beta12"

**Comment by mori2k12bln** [comment]
If I could help, please let me know. Otherwise the project maybe will get a Wordpress one with http://themes.themegoods2.com/capella/demo/

**Comment by arshad** [comment]
Thanks for the report. We'll look into the Pantheon setup. We have not "officially" launched on Pantheon yet so this might be a bit buggy.

Did you have issues with the local installation?

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
