### ISSUE TITLE
problems with local install (blank pages)

### ISSUE THREAD

**Issue by gusans** [openrestaurant/restaurant#16]
i'm having problems with the install assistant. downloaded 7.x-1.0-beta12.

after i fill the database info, next step gave a blank page. checked with phpmyadmin and the tables was created. no errors in apache logs. then i run install.php again and could continue just fine up to step 6.

at step 6 "configure site" when click on "Save and continue" get blank page again.

now i get these errors on errors.log

[Thu May 28 09:48:20.802864 2015] [:error] [pid 7644] [client myip:45297] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done
[Thu May 28 09:48:58.541771 2015] [:error] [pid 7921] [client myip:45310] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done
[Thu May 28 09:49:05.030935 2015] [:error] [pid 7921] [client myip:45320] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done
[Thu May 28 09:49:08.659878 2015] [:error] [pid 7819] [client myip:45321] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done
[Thu May 28 09:49:21.902976 2015] [:error] [pid 2066] [client myip:45328] PHP Fatal error:  Unsupported operand types in /var/www/html/resto/includes/install.core.inc on line 618, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en
[Thu May 28 09:49:34.651940 2015] [:error] [pid 7914] [client myip:45335] PHP Fatal error:  Unsupported operand types in /var/www/html/resto/includes/install.core.inc on line 618, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en
[Thu May 28 09:49:46.870963 2015] [:error] [pid 7640] [client myip:45336] PHP Fatal error:  Unsupported operand types in /var/www/html/resto/includes/install.core.inc on line 618, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en
[Thu May 28 09:50:12.166173 2015] [:error] [pid 7819] [client myip:45372] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done
[Thu May 28 10:31:44.502365 2015] [:error] [pid 7917] [client myip:46213] PHP Fatal error:  Call to undefined function field_attach_form() in /var/www/html/resto/modules/user/user.module on line 3797, referer: http://mysite.com/resto/user
[Thu May 28 10:32:16.814982 2015] [:error] [pid 8211] [client myip:46232] PHP Fatal error:  Call to undefined function field_attach_load() in /var/www/html/resto/includes/entity.inc on line 316, referer: http://mysite.com/resto/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done

**Comment by arshad** [comment]
Thanks for the report. I'll take a look in a few min.

**Comment by arshad** [comment]
Can you try the dev version? The beta12 has some errors that we've fixed on dev. http://ftp.drupal.org/files/projects/restaurant-7.x-1.x-dev-core.zip

**Comment by gusans** [comment]
great! thanks for your quick reply. could install the dev version whitout any trouble.

it seems a very nice distro. thanks for your work on this!

just a few things i noted out of the box:

- after install, there are some database updates pending. running update.php works fine but display the error "Passing an empty first parameter to a migration constructor is now deprecated - pass through the arguments array passed to the leaf class instead."

- in menus page it display this error:
Notice: Undefined variable: views_row_class in include() (line 12 of /var/www/html/resto/profiles/restaurant/modules/contrib/radix_views/templates/radix-views-grid-plugin-style.tpl.php).

- the images of the teasers in "feature posts" and "feature events" blocks appears too big for the container. i temporary added (via firefox developer tools) the img-responsive class to the images and seems to solve the problem.

**Comment by arshad** [comment]
Thanks. We're working on those issues and have more things to show, including a new theme in the 1.0 release.

Thanks for letting us about these issues. Helps us make the product better for everyone.

**Comment by vikingdker** [comment]
Hello,
i can confirm its the same on dev version menu have same error ty.

**Comment by vikingdker** [comment]
Also in Administration/index/features/restaurant most of the features is overridden,

Administration/index/features/restaurant demo  not able to turn off demo, after saving setting turns on again.

ty.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
