### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by phillipclarke29** [openrestaurant/restaurant#17]
Can anybody point me in the right direction to add a background image to a new restaurant radix themed site

**Comment by arshad** [comment]
Hi Philip, are you using a custom theme or using the existing restaurant_radix theme?

**Comment by phillipclarke29** [comment]
restaurant_radix

**Comment by arshad** [comment]
If you go to `restaurant_radix/assets/stylesheets` you will see a `custom.css` file. Use this file to add your custom css code.

**Step 1:** Add your background image to the following directory: `restaurant_radix/assets/images`.
**Step 2:** In your `custom.css` file, add the following code:

```
body {
    background: url("../images/name-of-background-image.png") no-repeat center;
}
```

**Step 3:** Save and refresh your site.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
