### ISSUE TITLE
Drupal core v7.38 drupal.org release

### ISSUE THREAD

**Issue by marcrobinsone** [openrestaurant/restaurant#18]
Hi there - when are you planning to reflect / release / update the profile with Drupal v7.38 codebase? Thanks!

**Comment by arshad** [comment]
We'll get to it today or tomorrow. We'll tag another release.

**Comment by marcrobinsone** [comment]
thanks Arshad, for the quick response. Hopefully DO will approve the release / build sooner due to the Father's day weekend. Cheers

**Comment by jollysolutions** [comment]
Any news?

**Comment by arshad** [comment]
We pushed an update for this to the latest dev. Let's check if it's building correctly and we can then tag for a new RC release.

**Comment by arshad** [comment]
Looks like the build failed on drupal.org. Just pushed to another build. https://www.drupal.org/node/1942268

I'll update here as soon as it's ready.

**Comment by arshad** [comment]
We've updated to the latest Drupal. Thanks.
