### ISSUE TITLE
Erratic slideshow behaviour on page load

### ISSUE THREAD

**Issue by martinterryevans** [openrestaurant/restaurant#19]
When the slideshow loads initially or when viewed in portrait mode on a Galaxy tablet there is extra space below the slides with faded grey background - see screenshot
![restslides](https://cloud.githubusercontent.com/assets/3635816/8355294/5b85bbd4-1b46-11e5-901c-0d66b1a6d59f.png)

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
