### ISSUE TITLE
Menu Block 7.x-2.5 breaks Radix

### ISSUE THREAD

**Issue by dropper99** [openrestaurant/restaurant#2]
I have been trying to keep my installation up to date and ran across a problem when I tried to update Menu Block to it's newest version, 7.x-2.5.  I was getting this error:

Notice: Undefined variable: sidebar_first in /xxxx/xxxx/drupal7/profiles/restaurant/themes/radix/templates/system/maintenance-page.tpl.php on line 27

Restaurant Radix is my theme.

Rolling back to 2.4 resolves this issue. Just thought I'd give you a heads up.

**Comment by arshad** [comment]
We'll look into it. Thanks for the report.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
