### ISSUE TITLE
Events views exposed filters not working

### ISSUE THREAD

**Issue by martinterryevans** [openrestaurant/restaurant#20]
The taxonomy term filter settings are set to use the wrong vocabulary ( should be Event categories not Blogs.
Also the Keywords filter is not working - to fix :
The view format needs to be set to Panel Fields  and Title and Body fields need to be selected to allow the Global Combine fields filter felds to be selected

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
