### ISSUE TITLE
During Install got PHP Fatal error:  Call to a member function processImport() on a non-object 

### ISSUE THREAD

**Issue by devalphabeta** [openrestaurant/restaurant#21]
PHP Fatal error:  Call to a member function processImport() on a non-object in /var/www/openrest.revuprewards/profiles/restaurant/modules/panopoly/panopoly_core/panopoly_core.module on line 302, referer: http://foo.com/install.php?profile=restaurant&welcome=done&locale=en&installation_type=standard&select_installation_type=done&op=start&id=3

Version: restaurant-7.x-1.0-rc2-core.zip

**Comment by arshad** [comment]
Looking into this. Thanks for the report.

**Comment by arshad** [comment]
This issue was moved to openrestaurant/support#5
