### ISSUE TITLE
An AJAX HTTP error occurred During Installation

### ISSUE THREAD

**Issue by Playmice** [openrestaurant/restaurant#23]
Hello. When installing, I get this error (Stage 5 of 10)

Error message

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://restaurant.dd:8080/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done&db_import_filename=C%3A%5CServer%5CDrupal%5Cwww%5Crestaurant/profiles/restaurant/db/restaurant.mysql&id=1&op=do StatusText: OK ResponseText: Open Restaurant | Drupal @import url("http://restaurant.dd:8080/modules/system/system.base.css?0"); @import url("http://restaurant.dd:8080/modules/system/system.messages.css?0"); @import url("http://restaurant.dd:8080/modules/system/system.theme.css?0"); @import url("http://restaurant.dd:8080/modules/user/user.css?0"); @import url("http://restaurant.dd:8080/modules/system/system.admin.css?0"); @import url("http://restaurant.dd:8080/modules/system/system.maintenance.css?0"); @import url("http://restaurant.dd:8080/profiles/restaurant/themes/radix/assets/stylesheets/radix-style.css?0"); @import url("http://restaurant.dd:8080/profiles/restaurant/themes/radix/assets/stylesheets/radix-print.css?0"); Open Restaurant Installation tasksStep 1Welcome(done)Step 2Installation type(done)Step 3Verify requirements(done)Step 4Set up database(done)Step 5Import profile(active)Step 6Configure siteStep 7Install demo contentStep 8Configure restaurantStep 9Post installStep 10Completed Import profile Step 5 of 10 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;/*!40101 SET @OLD_COLL' at line 1

![capture](https://cloud.githubusercontent.com/assets/11166933/10881581/396f650c-8164-11e5-83cd-ce80f23cdc44.JPG)

**Comment by arshad** [comment]
This issue was moved to openrestaurant/support#3
