### ISSUE TITLE
How can I change the default currency from $

### ISSUE THREAD

**Issue by phillipclarke29** [openrestaurant/restaurant#3]
How do you change menu prices from $ to say £

**Comment by arshad** [comment]
Step 1: Make sure you have Field UI module enabled. If not go to Modules and enable Field UI.
Step 2: Go to Structure → Field Collections.
Step 3: Click on Manage Fields next to **field_menu_types**.
Step 4: Edit the Price field.
Step 5: Change the value of Prefix from $ to £.
Step 6: Save.

![price___drupal_restaurant](https://cloud.githubusercontent.com/assets/124599/6750550/c83b1482-cf14-11e4-9165-e8fcd2a4a0b3.png)

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
