### ISSUE TITLE
Time slots with restaurant reservation

### ISSUE THREAD

**Issue by malasaad82** [openrestaurant/restaurant#4]
Hi,
What should I need if I would like to add more fields for Time slots ...  And if its booked with confimed status then its not selectable.

Time for booking:   
09.00-10.00
10.00-11.00
11.00-12.00
12.00-13.00

etc..

Any help about that..  

Thanks a lot!

**Comment by arshad** [comment]
You can do that by changing the settings for the date field at /admin/structure/types/manage/reservation/fields/field_reservation_date (Make sure you have the field ui module enabled. See Modules from the admin menu)

To restrict the dates, you need to look into https://www.drupal.org/project/date_restrictions and might need some custom codes to hook it into the reservation system

**Comment by malasaad82** [comment]
Hi,
Thanks for your answer! .. I really tried to make it .. and here is
screenshot:
I created select list field for times...

but I dont know really how should I make the condition.. If this node with
this date already has confirmed status for this time then this time will
not be bookable anymore for this date...

I tried to use rules.. and Field Validation .. but I don't know how really
Can I make this condition...  Please any more help and if you could make it
and tell me how much it could cost..

*Thanks*
[image: Inline images 1]
[image: Inline images 2]

**Comment by malasaad82** [comment]
Hi Arshed,
I just wanna say I already made it .. I used a module called  unique field
.. And I made the time and date fields unique in combination :) .. But I
just need to show that this time is not selectable if user cant select it.

Thanks...

**Comment by arshad** [comment]
Did you try a `hook_form_alter`?

**Comment by malasaad82** [comment]
No really..  please could you do that and tell me what cost or should I
find freelancer. ?

**Comment by arshad** [comment]
I'll get back to you on this today.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
