### ISSUE TITLE
minor error in screen.css file

### ISSUE THREAD

**Issue by iamachine** [openrestaurant/restaurant#6]
# Location:
restaurant-7.x-1.0-beta10/profiles/restaurant/themes/restaurant_radix/assets/stylesheets/screen.css

# Issue 
Lines 1200,1201 are repeated at lines 1202, 1203 with different values

# Sample:
 Lines 11996-12004:
/* line 48, ../sass/partials/_layout.scss */
.footer {
  background-color: #e7e7e7;
  color: #555555;
  padding-top: 20px;
  padding-bottom: 20px;
  padding-top: 60px;
  padding-bottom: 60px;
}

Could be padding right and left missing or extraneous padding top, bottom.

**Comment by arshad** [comment]
Thanks. We'll push a fix.

**Comment by iamachine** [comment]
Arshad,  
Also on the css side of things, I found that videos posted using the built in wysiwyg do not resize well.  You can scroll bars see in two images posted below.  I added the following custom css to fix it. see final image below.  

The sample css below is a real hack as it only targets .media-youtube-video and not Vimeo or uploaded video files.  (I haven't tested these, I assume they will break as well)

Maybe you could look into the proper place to place similar css code to work with all videos uploaded through the Restaurant Distribution.

To find more about this method, search for "padding-bottom: 56.25%; /* 16:9 */"

I can open a new issue if you think this should be logged and tracked.  On a personal note, Thank-You for all the work you have done on this and other related projects.
-Chris

/*Causes Youtube Videos to be responsive */
    .media-youtube-video{

        position: relative;
        padding-bottom: 56.25%; /* 16:9 */
        padding-top: 25px;
        height: 0;
    }
    .media-youtube-player  {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    } 
![youtube not resizing in blog entry](https://cloud.githubusercontent.com/assets/7613312/7008686/b4c34a5c-dc5a-11e4-8748-3f2ac25b6641.JPG)

![youtube not resizing in blog entry2](https://cloud.githubusercontent.com/assets/7613312/7008875/d8c99f36-dc5b-11e4-86c2-dc607de64f9c.JPG)

![fixed youtube not resizing in blog entry2](https://cloud.githubusercontent.com/assets/7613312/7008883/ea76f06c-dc5b-11e4-98b2-c27c075ca8bd.JPG)

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
