### ISSUE TITLE
Show Thanks message after submit the reservation

### ISSUE THREAD

**Issue by malasaad82** [openrestaurant/restaurant#7]
Hi,
How could I add a message after submit the reservation form.?

Thanks

**Comment by arshad** [comment]
A reservation is a node/content type. So you can either do it using code or a contrib module.

Contrib: https://www.drupal.org/project/csm
Code: http://drupal.stackexchange.com/questions/91631/how-to-show-a-message-after-a-node-form-is-submitted

**Comment by malasaad82** [comment]
Thank you for that ,I will try it....  Sorry If I am asking a lot.. How did you add the class for each status ( confirmed , canceled.. pending..  ) ..

Thank you

**Comment by arshad** [comment]
We're adding it in code in a theme function. See https://github.com/drupalrestaurant/restaurant_reservation/blob/7.x-1.x/restaurant_reservation.theme.inc#L10
and https://github.com/drupalrestaurant/restaurant_reservation/blob/7.x-1.x/restaurant_reservation.module#L312

Ask as many questions as you need. By asking questions you're helping us write documentation :)

**Comment by malasaad82** [comment]
Thank you :) ... Okay one more question so :D .. I got problem with reservations views ,  and exactly with views bulk operation , its doesnot work and the problem from the UPDATE STATUS button if I delete it from the views then the views bulk operation works fine..  any way to fix that.. Thanks

And btw , I fixed the time issue we had talk about it before , but could I share the code with you if you could check if its good enough, and if you could make it as feature with your code :)

![image](https://cloud.githubusercontent.com/assets/9867797/6988042/a8267a3a-da4d-11e4-929a-6f2ee11a8388.png)

![image](https://cloud.githubusercontent.com/assets/9867797/6988045/afc982b4-da4d-11e4-9f32-b645d4c381ff.png)

**Comment by arshad** [comment]
I'll take a look at the views bulk operation bug. 

Yes you can share the code. Can you put it in a gist? Thanks.

**Comment by malasaad82** [comment]
I will email it for you .... but you need to create some extra fields ,I will send it as well..

**Comment by malasaad82** [comment]
Hi Arshad,
I uploaded the code here you find the module
https://gist.github.com/malasaad82/cae9846dcd5880d2baba

and here you find the files you can import them using bundle copy
https://gist.github.com/malasaad82/2fce26393adf2083051f

**Comment by arshad** [comment]
This issue was moved to openrestaurant/support#8
