### ISSUE TITLE
Change bage_banner text/color 

### ISSUE THREAD

**Issue by jaxpax** [openrestaurant/restaurant#8]
Hi!
I have made som changes in the restaurant installation profile and would like to change the default page banner text ***The Drupal Distribution to kickstart your restaurant website*** and the color, but cant find where the this info comes from. I have made changes in the page_banner.csv but still the original text and colors shows up after the installation. Where does this info origin from?

**Comment by malasaad82** [comment]
Hello there!
its in the panel page , you will find it if you go to : 
structure then pages then click edit page-home ...  then click on Content 
![image](https://cloud.githubusercontent.com/assets/9867797/6988390/3cf4d780-da51-11e4-8ee8-ab447038fed4.png)

then edit the pane you will find it there
![image](https://cloud.githubusercontent.com/assets/9867797/6988397/49a9a668-da51-11e4-9294-fdd0a0c8ff1f.png)

![image](https://cloud.githubusercontent.com/assets/9867797/6988400/52659d3e-da51-11e4-96b9-34f14020b6d3.png)

**Comment by arshad** [comment]
I've made a quick screencast here: https://www.dropbox.com/s/asqcetwm8syemni/restaurant-change-banner.mp4?dl=0

**Comment by malasaad82** [comment]
Arshad , please give me your email, waiting for you.

**Comment by jaxpax** [comment]
Thanks but I think my description was unclear. What I wanted to do was to alter the text and color in the installation profile so that the new text/color would be loaded next time I wanted to install a new site.

I noticed that the information for the Quick installation is gathered from the restaurant/db/restaurant.mysql.

I have tried to alter the values in the ***field_data_field_page_banner_text*** table, exporting the new db in to the db folder. The problem is that I can't get the installation to work with the new dump. I get this strange error...

**Comment by arshad** [comment]
What's the error?

**Comment by jaxpax** [comment]
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://localhost:8888/test/install.php?profile=restaurant&welcome=done&locale=en&installation_type=quick&select_installation_type=done&db_import_filename=/Applications/MAMP/htdocs/test/profiles/restaurant/db/restaurant.mysql&id=1&op=do StatusText: Internal Server Error ResponseText:

**Comment by jaxpax** [comment]
But still it seems that all the tables, with the edited values gets in to place during "Import profile"...

**Comment by jaxpax** [comment]
Looking in to the original dump there are 8011 rows, so no, not everything gets in to place it seems

**Comment by jaxpax** [comment]
Just to make sure I haven't messed up any of the files in the installation profile I tested to import an exported dump from the original restaurant/db/restaurant.mysql, during installation. But the problem remains the same.

**Comment by jaxpax** [comment]
It would be interesting to know about how the db dump is made, the workflow from configuring the site to creation of the restaurant.mysql

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
