### ISSUE TITLE
Strict warning message when updating reservation-status

### ISSUE THREAD

**Issue by jaxpax** [openrestaurant/restaurant#9]
Strict warning: Only variables should be passed by reference in restaurant_reservation_send_update_status_mail() (line 189 of /profiles/restaurant/modules/restaurant/restaurant_reservation/restaurant_reservation.module).

This seems to be a PHP-version related problem. This warning shows up in environments running PHP 5.4 and up. I'm developing on Acquia cloud where PHP 5.3 is deprecated for security reasons.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
